[project]
name = "pyfetch_wrapper"
version = "0.1"

dependencies = [
  'shiny',
  'shinylive',
  'python_version < 3.8',
]

[project.optional-dependencies]
tests = [
  'fastapi',
  'pytest',
  'pytest-asyncio',
  'httpx'
]