name: Run PyTest

on: workflow_dispatch

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: |
        python -m pip install --upgrade pip 
        pip install pytest pytest-asyncio fastapi httpx uvicorn
    - name: Install package
      run: |
        python -m pip install -e .
    - name: Test Endpoints and pyfetch-mimic
      run: python src_test_webserver/main.py &
           PID=$! &&
           sleep 5 &&
           pytest -vv test &&
           kill -INT $PID